"""empty message

Revision ID: 738df2335ec7
Revises: 
Create Date: 2020-01-05 18:09:49.245193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738df2335ec7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('group', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camp_end_date'), 'camp', ['end_date'], unique=False)
    op.create_index(op.f('ix_camp_group'), 'camp', ['group'], unique=False)
    op.create_index(op.f('ix_camp_key'), 'camp', ['key'], unique=True)
    op.create_index(op.f('ix_camp_location'), 'camp', ['location'], unique=False)
    op.create_index(op.f('ix_camp_name'), 'camp', ['name'], unique=False)
    op.create_index(op.f('ix_camp_start_date'), 'camp', ['start_date'], unique=False)
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_of_seats', sa.Integer(), nullable=True),
    sa.Column('starting_location', sa.String(length=140), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('linked_camp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['linked_camp'], ['camp.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation_req',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestor_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status_pending', sa.Boolean(), nullable=True),
    sa.Column('status_accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requestor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('reserved', sa.Boolean(), nullable=True),
    sa.Column('taken', sa.Boolean(), nullable=True),
    sa.Column('related_car', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_car'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('assigned_seat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_seat'], ['seat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('seat')
    op.drop_table('reservation_req')
    op.drop_table('car')
    op.drop_index(op.f('ix_camp_start_date'), table_name='camp')
    op.drop_index(op.f('ix_camp_name'), table_name='camp')
    op.drop_index(op.f('ix_camp_location'), table_name='camp')
    op.drop_index(op.f('ix_camp_key'), table_name='camp')
    op.drop_index(op.f('ix_camp_group'), table_name='camp')
    op.drop_index(op.f('ix_camp_end_date'), table_name='camp')
    op.drop_table('camp')
    # ### end Alembic commands ###
